#!/bin/bash
#
# Ref: https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md


# Determine necessary parameters
# -- EXEC command
EXEC=" run --rm ";
if [ "$(docker ps -q -f name=openvpn)" ]; then
  # Docekr is running
  EXEC=" exec "
else
  # Docker is stoped
  EXEC=" run --rm "
fi

# -- Client name
echo ""
echo "=========================== All Users =============================="
docker compose ${EXEC} openvpn ovpn_listclients
echo "===================================================================="
echo "[input] Please input the target clients."
read -p "> " client_name


# Write the client conf file (.ovpn)
docker compose ${EXEC} openvpn ovpn_revokeclient ${client_name} remove


# List all current clients
echo ""
echo "=========================== All Users =============================="
docker compose ${EXEC} openvpn ovpn_listclients
echo "===================================================================="
echo ""
